sonar.projectKey=Christoooophe_devops_cours_next
sonar.organization=christoooophe
sonar.sources=app
sonar.tests=app/_tests_
sonar.javascript.coveragePlugin=jest
sonar.coverage.exclusions=**/node_modules/**
