sonar.projectKey=Christoooophe_devops_cours_next
sonar.organization=christoooophe

sonar.sources=app
sonar.tests=app/__tests__
sonar.test.inclusions=app/__tests__/**/*

sonar.exclusions=**/node_modules/**,**/.next/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
