name: CI
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Start container
        run: docker compose up -d

      - name: Install dependencies
        run: docker run --rm my-app-app-1 npm install

      - name: Build app
        run: docker run --rm my-app-app-1 npm run build

      - name: Start  app
        run: docker run --rm my-app-app-1 npm run start &

      - name: Run Vitest
        run: docker docker run --rm my-app-app-1 npm test

      - name: Stop app
        if: always()
        run: docker compose down --remove-orphans
