name: CI
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Build app
        run: docker compose run --rm app sh -c "npm install && npm run build"

      - name: Start app
        run: docker compose run --rm app sh -c "npm run start"

      - name: Run Vitest
        run: docker compose run --rm app sh -c "npm test"
